import type { Settings } from "../types";

export const DEFAULT_SETTINGS: Settings = {
  default_save_dir: "",
  default_mode: "rect",
  theme: "dark",
  delay_seconds: 0,
  auto_copy: true,
  auto_save: false,
  filename_template: "snip-{yyyy}{MM}{dd}-{HH}{mm}{ss}",
  show_notification: true,
  notification_timer_seconds: 3,
  close_to_tray: true,
  start_minimized: false,
  default_format: "png",
  pen_color: "#ff3b30",
  pen_thickness: 3,
  hotkey_rect: "Shift+Super+S",
  hotkey_fullscreen: "Shift+Super+F",
  hotkey_window: "Shift+Super+W",
  hotkey_active_window: "Shift+Super+A",
  hotkey_toggle_app: "Shift+Super+D",
  rect_require_enter: false,
  recording_format: "mp4",
  recording_fps: 30,
  recording_microphone: false,
  recording_microphone_device: "",
  recording_system_audio: false,
  recording_show_cursor: true,
  recording_click_highlight: false,
  recording_countdown_seconds: 3,
  recording_max_duration_seconds: 0,
  recording_system_audio_device: "",
};
